// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if we're on a password reset page with recovery hash BEFORE initializing client
// This prevents Supabase from auto-consuming the recovery tokens
const isRecoveryFlow = typeof window !== 'undefined' && 
  window.location.hash.includes('type=recovery');

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // CRITICAL: Disable auto-detection of session in URL for recovery flows
    // This allows ResetPasswordForm to manually handle the tokens
    detectSessionInUrl: !isRecoveryFlow,
    // Use PKCE flow for better security
    flowType: 'pkce',
  }
});

export const clearAuthTokens = async (): Promise<void> => {
  try {
    await supabase.auth.signOut();
    // Clear all Supabase-related localStorage items
    const keys = Object.keys(localStorage);
    keys.forEach(key => {
      if (key.includes('supabase') || key.includes('auth') || key.startsWith('sb-')) {
        localStorage.removeItem(key);
      }
    });
    // Clear sessionStorage as well
    sessionStorage.clear();
  } catch (error) {
    console.error('Error clearing auth tokens:', error);
    // Even if signOut fails, clear localStorage
    const keys = Object.keys(localStorage);
    keys.forEach(key => {
      if (key.includes('supabase') || key.includes('auth') || key.startsWith('sb-')) {
        localStorage.removeItem(key);
      }
    });
    sessionStorage.clear();
    throw error;
  }
};

export const handleAuthError = async (error: any): Promise<void> => {
  // Check if the error is related to authentication/session issues
  const isAuthError = 
    error?.message?.includes('Invalid Refresh Token') ||
    error?.message?.includes('Refresh Token Not Found') ||
    error?.message?.includes('JWT expired') ||
    error?.message?.includes('session_not_found') ||
    error?.status === 401 ||
    error?.status === 403;

  if (isAuthError) {
    console.warn('Authentication error detected, clearing tokens:', error.message);
    try {
      await clearAuthTokens();
      // Optionally redirect to login page
      // window.location.href = '/login';
    } catch (clearError) {
      console.error('Error clearing tokens after auth error:', clearError);
    }
  } else {
    // Log non-auth errors for debugging
    console.error('Non-auth error:', error);
  }
};